apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: authentication-service-

commonAnnotations:
  team: team4

labels:
- includeSelectors: true
  pairs:
    app: authentication-service

resources:
- github.com/mauriciodm1998/kustomization/base?ref=v1.0.4